# Generated by Django 5.2.7 on 2025-11-03 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('portada', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Portada')),
                ('anioLanzamiento', models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1888)], verbose_name='Año de Lanzamiento')),
            ],
            options={
                'verbose_name': 'Película del Catálogo',
                'verbose_name_plural': 'Películas del Catálogo',
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Lista')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_personalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('peliculas', models.ManyToManyField(blank=True, related_name='listas', to='Peliculas.pelicula', verbose_name='Películas en la Lista')),
            ],
            options={
                'verbose_name': 'Lista Personalizada',
                'verbose_name_plural': 'Listas Personalizadas',
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
