# Generated by Django 5.2.7 on 2025-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(default='desconocido', max_length=50, verbose_name='Genero pelicula'),
        ),
    ]
